### Pytorch 

### Tensors
   Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing

In [2]:
import torch
x = torch.empty(5, 3)
x

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

### Construct a randomly initialized matrix

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0077, 0.1027, 0.1199],
        [0.4654, 0.2141, 0.0852],
        [0.8137, 0.3030, 0.7518],
        [0.4385, 0.1584, 0.1304],
        [0.3840, 0.2174, 0.8941]])


### Construct a matrix filled zeros and of dtype long:

In [7]:
x = torch.zeros(5, 3)
print(x)


 0  0  0
 0  0  0
 0  0  0
 0  0  0
 0  0  0
[torch.FloatTensor of size 5x3]



### Construct a tensor directly from data:

In [7]:
x1 = torch.tensor([5.5, 3])
print(x1)

tensor([5.5000, 3.0000])


In [6]:
print(torch.__version__)

0.4.1


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


### addition 

In [14]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

y = torch.rand(5, 3,dtype=torch.double)    # override dtype!
print(y) 

add=torch.add(x,y)
print("addition=")
print(add)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.9275, 0.6126, 0.1622],
        [0.3955, 0.9286, 0.9619],
        [0.6749, 0.6163, 0.8347],
        [0.5321, 0.0104, 0.7552],
        [0.8732, 0.9078, 0.7099]], dtype=torch.float64)
addition=
tensor([[1.9275, 1.6126, 1.1622],
        [1.3955, 1.9286, 1.9619],
        [1.6749, 1.6163, 1.8347],
        [1.5321, 1.0104, 1.7552],
        [1.8732, 1.9078, 1.7099]], dtype=torch.float64)


### Addition: providing an output tensor as argument

In [19]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.4078, 0.8334, 1.2600],
        [1.4493, 1.1657, 0.7873],
        [1.3419, 1.3547, 1.0221],
        [0.4543, 0.8498, 0.3101],
        [0.6986, 0.6308, 0.8790]])


In [ ]:
### Converting NumPy Array to Torch Tensor