In [0]:
# http://pytorch.org/
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.1-{platform}-linux_x86_64.whl torchvision
import torch
from torch.autograd import Variable 

In [0]:
### pytorch GPU and its operation

In [0]:
# checking the GPU and its name
if torch.cuda.is_available():
  print('cuda is supported')
else:
  print('GPU is not supported')
  

cuda is supported


In [0]:
# check the no of GPU attached in the CPU
torch.cuda.device_count()

1

In [0]:
# Find Device Name
torch.cuda.get_device_name(0)

'Tesla K80'

In [0]:
# making a tensor to GPU
tf=torch.FloatTensor([11.34])
tf=tf.cuda(0)
print(tf)

tensor([11.3400], device='cuda:0')


In [0]:
# create a tensor in cuda directly
t2=torch.cuda.FloatTensor([2.3])
print(t2)

tensor([2.3000], device='cuda:0')


In [0]:
# bring the Tensor to cpu
t2=t2.cpu()
print(t2)

tensor([2.3000])


In [0]:
# Use Device context, we can write a block of variable and operation within it
with torch.cuda.device(0):
  t5=torch.cuda.IntTensor([2,3,4])
  t6=torch.cuda.IntTensor([5,6,7])
  result=t5+t6
  print(result)

tensor([ 7,  9, 11], device='cuda:0', dtype=torch.int32)


In [0]:
# here we are creating a cuda GPU block but still we are not adding variable in GPU so it is not created in GPU
with torch.cuda.device(0):
  a=torch.Tensor([1,2,3])
  b=torch.Tensor([4,5,6])
  c=a+b
  print(c)

tensor([5., 7., 9.])


In [0]:
# asign GPU tensor in variable
v3=Variable(torch.cuda.FloatTensor([123]))
print(v3)

vb1=torch.cuda.FloatTensor([11.90])
vb2=Variable(vb1, requires_grad=True)
print(vb2)

tensor([123.], device='cuda:0')
tensor([11.9000], device='cuda:0', requires_grad=True)


TypeError: ignored