# Confirm TensorFlow can see the GPU

Simply select "GPU" in the Accelerator drop-down in Notebook Settings (either through the Edit menu or the command palette at cmd/ctrl-shift-P).

In [0]:
### Tensor, variable 

In [0]:
# http://pytorch.org/
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.1-{platform}-linux_x86_64.whl torchvision
import torch
import numpy as np

In [0]:
# creating tensor by calling Constructor
t=torch.Tensor([1.2,3.4])
print(t)

tensor([1.2000, 3.4000])


In [0]:
# creating a tensor by calling factory method
t1=torch.tensor([1,2,3])
print(t1)

tensor([1, 2, 3])


In [0]:
from torch.autograd import Variable

In [0]:
# variable declaration
v=Variable(torch.Tensor([[1,2,3],[4,5,6]]), requires_grad=True)
print(v)
print(v.size())
print(v.dim())

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.Size([2, 3])
2


In [0]:
# tensor from numpy array
n=np.array([1,2,3,4])
tn=torch.Tensor(n)
print(tn)

tensor([1., 2., 3., 4.])


In [0]:
# int tensor, float tensor
iT=torch.IntTensor([1,2,3,4])
print(iT)

# float tensor
ITF=torch.FloatTensor([1.2,3.0,4.5])
print(ITF)

tensor([1, 2, 3, 4], dtype=torch.int32)
tensor([1.2000, 3.0000, 4.5000])


In [0]:
# #### VARIABLE ########################################################################

In [0]:
v=Variable(torch.Tensor([11.2]), requires_grad=True)

y=v*2
print('v=',v)
print('y=',y)

('v=', tensor([11.2000], requires_grad=True))
('y=', tensor([22.4000], grad_fn=<MulBackward>))


In [0]:
print(v.data)
print(y.data)

tensor([11.2000])
tensor([22.4000])


In [0]:
### grad function
print(v.grad_fn)
print(y.grad_fn)

None


In [0]:
### backward function
y.backward()

In [0]:
print(v.grad)
print(y.grad)

tensor([2.])
None
